
project_id = "lgblicqyurcttmlguwsd"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[realtime]
enabled = true

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[functions.generate-with-image]
verify_jwt = false

[functions.generate-flux-pro]
verify_jwt = false
