
project_id = "lgblicqyurcttmlguwsd"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost:54321"

[functions]
[functions.ask-ia]
verify_jwt = false
