
project_id = "lgblicqyurcttmlguwsd"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
external_url = "https://supabase.io/dashboard"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[functions]
[functions.ask-ia]
verify_jwt = true
